# Labeler testing config
documentation:
  - '*.md'
frontend:
  - '*.html'
workflow:
  - '**/*.yml'
  - '**/*.yaml'
question:
  - '*.txt'
release:
  - base-branch: 'main'
information:
  - 'yamlfiles/*'
  - 'guides/*'
Decebal:
  - '*.txt'