# Labeler testing config
documentation:
  - '*.md'
frontend:
  - '*.html'
workflow:
  - '**/*.yml'
  - '**/*.yaml'
question:
  - '*.txt'
release:
  - base-branch: 'main'
information:
  - changed-files:
    - any-glob-to-any-file: ['yamlfiles/*', 'guides/*']
