name: Handle Issues
on:
  issues:
    types: [opened, edited, labeled, unlabeled, assigned]
jobs:
    event-info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub Context
              run: echo "${{ toJSON(github.event) }}"